################################## config all settings here ###################################

################################################ tethys_nginx ############################################
# change ssl.conf
TETHYS_NGINX_DOMAIN_NAME: 10.2.115.24

# enable maintenance page (Y or N)
TETHYS_NGINX_MAINTENANCE_ON: N

# Y or N
#(must set to Y currently)
TETHYS_NGINX_SSL_CERT_USE_PRODUCTION: Y
TETHYS_NGINX_SSL_CERT_CHAIN_CRT: ./nginx/certs/cert-chain.crt
TETHYS_NGINX_SSL_CERT_FILE_SERVER_CRT: ./nginx/certs/server.crt
TETHYS_NGINX_SSL_CERT_FILE_SERVER_KEY: ./nginx/certs/server.key

################################################ tethys_postgis ##################################################
# change postgis.env
TETHYS_POSTGIS_TETHYS_DEFAULT_PASS: pass_default
TETHYS_POSTGIS_TETHYS_DB_MANAGER_PASS: pass_db_manager
TETHYS_POSTGIS_TETHYS_SUPER_PASS: pass_super
TETHYS_POSTGIS_OPEN_PORTS: Y
TETHYS_POSTGIS_MAP_INTERNAL_5432_TO: 5435

############################################## tethys_main ################################################
# change the uid/gid to the user account who runs ./tethys_build script
TETHYS_MAIN_SERVICE_ACCOUNT_UID: 1000
TETHYS_MAIN_SERVICE_ACCOUNT_GID: 1000

#TETHYS_MAIN_GITHUB_REPO: https://github.com/tethysplatform/tethys.git
TETHYS_MAIN_GITHUB_REPO: https://github.com/zhiyuli/tethys.git

TETHYS_MAIN_BRANCH_NAME: 2d70c2dca6224be3f9b11465d1e32ab4c6fb5f2f

# change settings.py
# Do not contain 'pound sign #' or 'and sign &'
TETHYS_MAIN_SECRET_KEY: czh30tzX56F%+$v(a@&m*)*5%(p+(p1i6271i7l_63mer3m6+b

# python boolean variable: True or False
# True: use Django testing server
# False: use Gunicorn + Nginx serves static files
TETHYS_MAIN_DEBUG: False
# python boolean variable: True or False
TETHYS_MAIN_BYPASS_TETHYS_HOME_PAGE: True
# python boolean variable: True or False
TETHYS_MAIN_ENABLE_OPEN_SIGNUP: True

# python string (default: '/accounts/login/')
# see: https://docs.djangoproject.com/en/1.10/ref/settings/#login-url
# let user choose provider:  '/accounts/login/'
# set to login through HydroShare OAuth by default:  '/oauth2/login/hydroshare/'
# set to login through HydroShare-beta OAuth by default:  '/oauth2/login/hydroshare_beta/'
TETHYS_MAIN_LOGIN_URL: '/accounts/login/'

# OAuth Login
# Y or N
TETHYS_MAIN_HYDROSHARE_BACKEND: Y
# python string
TETHYS_MAIN_HYDROSHARE_BACKEND_MODULE: "tethys_services.backends.hydroshare.HydroShareOAuth2"
TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_KEY: y8w6FPhW1c5jGMsSfkkNyZ5LPt1v3SaLibkktRHz
TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_SECRET: yWGer4UOwkUyTYzpP15BU7SNzRZRt7H0iwxO5YhnC1bNJLyWU0eB0iPFRAhr9b4TM8tQdDOUvD5kqg86I3gxhiUjU5ay7kqN3VbnwNs1B9BCeXiVkMRRqvfiXYcYgMLP

# Y or N
TETHYS_MAIN_HYDROSHARE_BETA_BACKEND: N
# python string
TETHYS_MAIN_HYDROSHARE_BETA_BACKEND_MODULE: "tethys_services.backends.hydroshare_beta.HydroShareBetaOAuth2"
TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_BETA_KEY: NBv1zGvR1Gdw07QZMPvC3NvCOwPf2ch8uebTtMLI
TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_BETA_SECRET: 0gXWPZxPJBHLcA8JHkjztjtUuNp1LDhpoIWSrxBUo32bZerbU5b1ujuU80yhsfdOJEzQqQO6Wvad7O5W71JZqzvoHXp6CjFmPirpv8r6K3IJhBI0GvIJ4qD9x4SXqELt

# Y or N
TETHYS_MAIN_HYDROSHARE_PLAYGROUND_BACKEND: N
# python string
TETHYS_MAIN_HYDROSHARE_PLAYGROUND_BACKEND_MODULE: "tethys_services.backends.hydroshare_playground.HydroSharePlaygroundOAuth2"
TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_PLAYGROUND_KEY: B9SekrmKRpEhqaMOSUD883ExbT55e2Snbyrnk3A9
TETHYS_MAIN_SOCIAL_AUTH_HYDROSHARE_PLAYGROUND_SECRET: iFLgfSmbi9aXJh5e6EubvPo7ldguumLjdFCHAxJvrKUmY3y3iRixCzJTwEpcaEGa3YRCKz1KuRTQHSXhaecTHa2k8Qp90Gcnq2SS07vlAtege5o6rX1teVioGUF0gCWP

# change docker-compose.yml
# Y or N
TETHYS_MAIN_MOUNT_RENCI_FOLDER: N
TETHYS_MAIN_MOUNT_RENCI_FOLDER_PATH: /projects/water/nwm/
TETHYS_MAIN_OPEN_PORTS: Y
TETHYS_MAIN_MAP_INTERNAL_8000_TO: 8000
TETHYS_MAIN_MAP_INTERNAL_5555_TO: 5555
############################################## tethys_geoserver ##############################################
# change geoserver.env
TETHYS_GEOSERVER_ENABLED_NODES: 1
TETHYS_GEOSERVER_REST_NODES: 1
TETHYS_GEOSERVER_NUM_CORES: 2
# discard a request from queue after given seconds
TETHYS_GEOSERVER_MAX_TIMEOUT: 60
# max mem for each node
TETHYS_GEOSERVER_MAX_MEMORY: 2048
# min mem for each node
TETHYS_GEOSERVER_MIN_MEMORY: 1024
# limit file browser to data folder only
TETHYS_GEOSERVER_GEOSERVER_FILEBROWSER_HIDEFS: true

# Y or N
TETHYS_GEOSERVER_OPEN_PORTS: Y
TETHYS_GEOSERVER_MAP_INTERNAL_8181_TO: 8181
TETHYS_GEOSERVER_MAP_INTERNAL_8081_TO: 8081
TETHYS_GEOSERVER_MAP_INTERNAL_8082_TO: 8082
TETHYS_GEOSERVER_MAP_INTERNAL_8083_TO: 8083
TETHYS_GEOSERVER_MAP_INTERNAL_8084_TO: 8084

# change tethys_main/settings.py
# these settings are used by some legacy apps that dont read GeoServer info from Tethys Spatial Dataset Service
# Y or N: if Y, both GEOSERVER_URL_BASE and GEOSERVER_URL_SSL_BASE in settings.py will be
#         https://${TETHYS_NGINX_DOMAIN_NAME}:${TETHYS_GEOSERVER_SSL_ON_PORT}
TETHYS_GEOSERVER_FORCE_SSL: N
TETHYS_GEOSERVER_HTTP_ON_PORT: 8181
TETHYS_GEOSERVER_SSL_ON_PORT: 443
TETHYS_GEOSERVER_USER_NAME: admin
TETHYS_GEOSERVER_USER_PASSWORD: geoserver

############################################ tethys_n52wps #####################################################
# change n52wps.env
TETHYS_N52WPS_USERNAME: wps
TETHYS_N52WPS_PASSWORD: wps

# change docker-compose.yml
# Y or N
TETHYS_N52WPS_OPEN_PORTS: Y
TETHYS_N52WPS_MAP_INTERNAL_8080_TO: 8282
